### ISSUE TITLE
You broke it :(

### ISSUE THREAD

**Issue by liamcain** [wuub/SublimePTY#1]
Package Control updated me to latest version and now I'm getting the following error:
`Traceback (most recent call last):
      File "./sublime_plugin.py", line 327, in run_
      File "./sublimepty.py", line 20, in run
      File "./process.py", line 99, in __init__
    TypeError: super(type, obj): obj must be an instance or subtype of type`

Wasn't sure if you'd rather I post the error here or on the forum.  Figured here would be better...

**Comment by wuub** [comment]
Try restaring sublime. It should help :)

**Comment by liamcain** [comment]
You fixed it! haha
